site_name: Efesto documentation
theme:
    name: gitbook
nav:
    - Home: 'index.md'
    - Installing: 'installing.md'
    - Configuration: 'configuration.md'
    - The command line: 'cli.md'
    - Middlewares: 'middlewares.md'
    - Blueprints: 'blueprints.md'
    - Using the API: 'using-the-api.md'
    - Deploying: 'deploying.md'
    - Roadmap: 'roadmap.md'
